import Modal from '@/components/Modal'
import './globals.css'

export const metadata = {
  title: 'TRELLO 2.0',
  description: 'Generated by Rohit Gupta',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#f5f6f8]" >
        {children}
        <Modal />
      </body>
    </html>
  )
}
